 const Users = [
{
    "name": "Zlata",
    "lastname": "Tadic",
    "email": "zlata.tadic@example.com",
    "password": "viewsoni",
    "birthdate": "1988-02-22",
    "phoneNumber": "033-8088-702",
    "address": "Veroljuba Atanasijevića",
    "postalCode": "82231",
    "state": "Kolubara",
    "country": "Serbia",
    "image": "https://randomuser.me/api/portraits/women/87.jpg"
},
{
    "name": "Melodie",
    "lastname": "Abraham",
    "email": "melodie.abraham@example.com",
    "password": "viewsoni",
    "birthdate": "1995-03-02",
    "phoneNumber": "J62 D92-3326",
    "address": "Peel St",
    "postalCode": "P9D 9K0",
    "state": "Newfoundland and Labrador",
    "country": "Canada",
    "image": "https://randomuser.me/api/portraits/women/12.jpg"
},
{
    "name": "Aliya",
    "lastname": "Stålesen",
    "email": "aliya.stalesen@example.com",
    "password": "viewsoni",
    "birthdate": "1995-03-02",
    "phoneNumber": "J62 D92-3326",
    "address": "Peel St",
    "postalCode": "4332",
    "state": "Newfoundland and Labrador",
    "country": "Canada",
    "image": "https://randomuser.me/api/portraits/women/94.jpg"
},
{
    "name": "Mason",
    "lastname": "Wright",
    "email": "mason.wright@example.com",
    "password": "viewsoni",
    "birthdate": "1995-03-02",
    "phoneNumber": "J62 D92-3326",
    "address": "Peel St",
    "postalCode": "4332",
    "state": "Newfoundland and Labrador",
    "country": "Canada",
    "image": "https://randomuser.me/api/portraits/women/94.jpg"
},
{
    "name": "Henni",
    "lastname": "Lieske",
    "email": "henni.lieske@example.com",
    "password": "viewsoni",
    "birthdate": "1995-03-02",
    "phoneNumber": "J62 D92-3326",
    "address": "Peel St",
    "postalCode": "4332",
    "state": "Newfoundland and Labrador",
    "country": "Canada",
    "image": "https://randomuser.me/api/portraits/women/18.jpg"
},
{
    "name": "Joseph",
    "lastname": "Clarke",
    "email": "joseph.clarke@example.com",
    "password": "viewsoni",
    "birthdate": "1995-03-02",
    "phoneNumber": "J62 D92-3326",
    "address": "Peel St",
    "postalCode": "4332",
    "state": "Newfoundland and Labrador",
    "country": "Canada",
    "image": "https://randomuser.me/api/portraits/men/24.jpg",
},
{
    "name": "Rose",
    "lastname": "Novak",
    "email": "rose.novak@example.com",
    "password": "viewsoni",
    "birthdate": "1995-03-02",
    "phoneNumber": "J62 D92-3326",
    "address": "Peel St",
    "postalCode": "4332",
    "state": "Newfoundland and Labrador",
    "country": "Canada",
    "image": "https://randomuser.me/api/portraits/women/93.jpg",
},
{
    "name": "Svitlana",
    "lastname": "Staruh",
    "email": "svitlana.staruh@example.com",
    "password": "viewsoni",
    "birthdate": "1995-03-02",
    "phoneNumber": "J62 D92-3326",
    "address": "Peel St",
    "postalCode": "4332",
    "state": "Newfoundland and Labrador",
    "country": "Canada",
    "image": "https://randomuser.me/api/portraits/women/58.jpg",
},
{
    "name": "Rina",
    "lastname": "Morin",
    "email": "rina.morin@example.com",
    "password": "viewsoni",
    "birthdate": "1995-03-02",
    "phoneNumber": "J62 D92-3326",
    "address": "Peel St",
    "postalCode": "4332",
    "state": "Newfoundland and Labrador",
    "country": "Canada",
    "image": "https://randomuser.me/api/portraits/women/90.jpg",
},
{
    "name": "Thomas",
    "lastname": "Ray",
    "email": "thomas.ray@example.com",
    "password": "viewsoni",
    "birthdate": "1995-03-02",
    "phoneNumber": "J62 D92-3326",
    "address": "Peel St",
    "postalCode": "4332",
    "state": "Newfoundland and Labrador",
    "country": "Canada",
    "image": "https://randomuser.me/api/portraits/men/98.jpg",
},

]


module.exports = Users